# Generated by Django 2.2.7 on 2019-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='image',
            field=models.ImageField(default='blog/static/images/no-img.jpg', upload_to='blog'),
        ),
    ]
